FROM node:22-alpine

WORKDIR /app

# Install envsubst
RUN apk add --no-cache gettext
COPY package*.json ./

RUN npm install

COPY . .

# Build the React app
# RUN npm run build
# FROM nginx:alpine
# COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 5173

# CMD [ "npm", "run", "dev" , "--", "--host"]

# Generate env.js at runtime, then start the server
CMD ["sh", "-c", "envsubst < public/env.template.js > public/env.js && npm run dev -- --host"]