services:

  frontend:
    
    # image from doockerHub
    image: mario247/htcc-frontend-prod:${IMAGE_TAG:-latest}
    
    # image from local service
    # image: htcc-frontend-dev:1.0.0
    container_name: htcc-frontend-prod

    ports:
      - "3000:80"
    env_file:
      - .env
    # environment:
    #   API_URL: "${API_HOST_IP}"
    restart: always
    # networks:
    #   - htccm-network



  backend:

    # depends_on:
    #   - db
    # image from doockerHub
    image: mario247/htcc-backend-api-prod:${IMAGE_TAG:-latest}

    # image from local service
    # image: htcc-backend-api-dev:1.0.0
    container_name: htcc-backend-api-prod

    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    
    # networks:
    #   - htccm-network

#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     networks:
#       - htccm-network

# networks:
#   htccm-network:
#     driver: bridge
  